{
 "title": "DB_Dashboard_Longterm",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 0 },
   "options": {
    "content": "<h1><img src=\"https://www.company.org/logo.png\" width =\"100\" height =\"100\" alt=\"logo\"/>My Logo</h1>\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 7, "x": 10, "y": 0 },
   "options": {
    "content": "<br>\n<h1 style=\"color:white;\"><strong>Dashboard Longterm</strong></h1>\n\n\n"
   }
  },
  { "title": "Time", "type": "grafana-clock-panel", "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 } },
  {
   "title": "Number of Transactions per Minute",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short", "label": "Number of Transactions" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_database_xact_commit{group=\"database\", datname=\"postgres\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Number of Idle/ Active Sessions",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short", "label": "Number of Sessions" }
   ],
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{group=\"database\", datname=\"postgres\", state=~\"idle|idle in transaction|idle in transaction (aborted)\"}) by (instance)",
     "legendFormat": "{{instance}} (idle)"
    },
    {
     "expr": "pg_stat_activity_count{group=\"database\", datname=\"postgres\", state=\"active\"}",
     "legendFormat": "{{instance}} (active)"
    }
   ]
  },
  {
   "title": "Inserted/ Updated/ Fetched/ Returned Rows per Minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short", "label": "Number of Rows" }
   ],
   "targets": [
    {
     "alias": "fetched",
     "expr": "irate(pg_stat_database_tup_fetched{group=\"database\", datname=\"postgres\", instance=\"10.3.8.106:9187\"}[1m])\n\n",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}} Fetched",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "tup_fetched" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "fetched",
     "expr": "irate(pg_stat_database_tup_returned{group=\"database\", datname=\"postgres\", instance=\"10.3.8.106:9187\"}[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}} Returned",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "tup_fetched" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "expr": "irate(pg_stat_database_tup_inserted{group=\"database\", datname=\"postgres\", instance=\"10.3.8.106:9187\"}[1m])",
     "legendFormat": "{{instance}} Inserted"
    },
    {
     "expr": "irate(pg_stat_database_tup_updated{group=\"database\", datname=\"postgres\", instance=\"10.3.8.106:9187\"}[1m])",
     "legendFormat": "{{instance}} Updated"
    }
   ]
  },
  {
   "title": "Inserted/ Updated/ Fetched/ Returned Rows per Minute",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "Number of Rows" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_database_tup_fetched{group=\"database\", datname=\"postgres\", instance=\"10.3.8.100:9187\"}[1m])",
     "legendFormat": "{{instance }} Fetched"
    },
    {
     "expr": "irate(pg_stat_database_tup_returned{group=\"database\", datname=\"postgres\", instance=\"10.3.8.100:9187\"}[1m])",
     "legendFormat": "{{instance }} Returned"
    },
    {
     "alias": "fetched",
     "expr": "irate(pg_stat_database_tup_inserted{group=\"database\", datname=\"postgres\", instance=\"10.3.8.100:9187\"}[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance }} Inserted",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "tup_fetched" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "fetched",
     "expr": "irate(pg_stat_database_tup_updated{group=\"database\", datname=\"postgres\", instance=\"10.3.8.100:9187\"}[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance }} Updated",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "tup_fetched" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  }
 ]
}