{
 "title": "General_Overview_Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 0 },
   "options": {
    "content": "<h1><img src=\"https://www.company.org/logo.png\" width =\"100\" height =\"100\" alt=\"logo\"/>My Logo</h1>\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 7, "x": 10, "y": 0 },
   "options": {
    "content": "<br>\n<h1 style=\"color:white;\"><strong>Overview Server Health</strong></h1>\n\n\n"
   }
  },
  { "title": "Time", "type": "grafana-clock-panel", "gridPos": { "h": 3, "w": 5, "x": 19, "y": 0 } },
  {
   "title": "Database Server",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "(node_time_seconds{group=\"database\"} - node_boot_time_seconds{group=\"database\"}) / (60*60*24)"
    },
    {
     "expr": "instance:node_filesystem_avail:threshold{group=\"database\"} + on(instance, server_name) instance:node_memory_avail:threshold{group=\"database\"} + on (instance, server_name) instance:cpu_avg:threshold{group=\"database\"} or on(instance,server_name) (instance:up{group=\"database\"}*4)"
    }
   ]
  },
  {
   "title": "ETL Worker/ Scheduler",
   "type": "table",
   "gridPos": { "h": 12, "w": 10, "x": 13, "y": 3 },
   "targets": [
    {
     "expr": "(node_time_seconds{group=\"etl_worker\"} - node_boot_time_seconds{group=\"etl_worker\"}) / (60*60*24)"
    },
    {
     "expr": "instance:node_filesystem_avail:threshold{group=\"etl_worker\"} + on(instance, server_name) instance:node_memory_avail:threshold{group=\"etl_worker\"} + on (instance, server_name) instance:cpu_avg:threshold{group=\"etl_worker\"} or on(instance,server_name) (instance:up{group=\"etl_worker\"}*4)"
    }
   ]
  },
  {
   "title": "Research Repository",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "(node_time_seconds{group=\"research_repo\"} - node_boot_time_seconds{group=\"research_repo\"}) / (60*60*24)"
    },
    {
     "expr": "instance:node_filesystem_avail:threshold{group=\"research_repo\"} + on(instance, server_name) instance:node_memory_avail:threshold{group=\"research_repo\"} + on (instance, server_name) instance:cpu_avg:threshold{group=\"research_repo\"} or on(instance,server_name) (instance:up{group=\"research_repo\"}*4)"
    }
   ]
  },
  {
   "title": "ETL Repository",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "(node_time_seconds{group=\"repo\"} - node_boot_time_seconds{group=\"repo\"}) / (60*60*24)"
    },
    {
     "expr": "instance:node_filesystem_avail:threshold{group=\"repo\"} + on(instance, server_name) instance:node_memory_avail:threshold{group=\"repo\"} + on (instance, server_name) instance:cpu_avg:threshold{group=\"repo\"} or on(instance,server_name) (instance:up{group=\"repo\"}*4)"
    }
   ]
  }
 ]
}