{
 "title": "Sysadmin_Dashboard_Overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 0 },
   "options": {
    "content": "<h1><img src=\"https://www.company.org/logo.png\" width =\"100\" height =\"100\" alt=\"logo\"/>My Logo</h1>\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 6, "x": 11, "y": 0 },
   "options": {
    "content": "<br>\n<h1 style=\"color:white;\"><strong> Server Resources </strong></h1>\n\n\n"
   }
  },
  { "title": "Time", "type": "grafana-clock-panel", "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 } },
  {
   "title": "Database Server",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "((1 - avg(irate(node_cpu_seconds_total{group=\"database\", mode=\"idle\"}[5m])) by (instance)) * 100) or avg(instance:up{group=\"database\"}*99) by (instance)",
     "legendFormat": "Used CPU"
    },
    {
     "expr": "((1 - (node_memory_MemAvailable_bytes{group=\"database\"} / (node_memory_MemTotal_bytes{group=\"database\"}))) * 100) or on(instance,server_name) (instance:up{group=\"database\"}*99)",
     "legendFormat": "Used RAM"
    },
    {
     "expr": "(avg((1 - (node_filesystem_avail_bytes{group=\"database\", mountpoint=\"/\",fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes {group=\"database\", mountpoint=\"/\",fstype=~\"ext4|xfs\"})) * 100) by (instance)) or avg(instance:up{group=\"database\"}*99) by (instance)",
     "legendFormat": "Used Disk Space"
    },
    {
     "expr": "((1 - (node_filesystem_avail_bytes{group=\"database\", mountpoint=~\"/.+\",fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes {group=\"database\", mountpoint=~\"/.+\",fstype=~\"ext4|xfs\"})) * 100) or on(instance,server_name) (instance:up{group=\"database\"}*99)"
    }
   ]
  },
  {
   "title": "ETL Worker/ Scheduler",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "((1 - avg(irate(node_cpu_seconds_total{group=\"etl_worker\", mode=\"idle\"}[5m])) by (instance)) * 100) or avg(instance:up{group=\"etl_worker\"}*99) by (instance)",
     "legendFormat": "Used CPU"
    },
    {
     "expr": "(((1 - (node_memory_MemAvailable_bytes{group=\"etl_worker\"} / (node_memory_MemTotal_bytes{group=\"etl_worker\"}))) * 100) or on(instance,server_name) (instance:up{group=\"etl_worker\"}*99))",
     "legendFormat": "Used RAM"
    },
    {
     "expr": "avg((1 - (node_filesystem_avail_bytes{group=\"etl_worker\", mountpoint=\"/\",fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes {group=\"etl_worker\",  mountpoint=\"/\",fstype=~\"ext4|xfs\"})) * 100) by (instance) or avg(instance:up{group=\"etl_worker\"}*99) by (instance)",
     "legendFormat": "Used Disk Space"
    },
    {
     "expr": "((1 - (node_filesystem_avail_bytes{group=\"etl_worker\", mountpoint=~\"/.+\",fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes {group=\"etl_worker\",  mountpoint=~\"/.+\",fstype=~\"ext4|xfs\"})) * 100) or on(instance) (instance:up{group=\"etl_worker\"}*99)"
    }
   ]
  },
  {
   "title": "Research Repository",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "((1 - avg(irate(node_cpu_seconds_total{group=\"research_repo\", mode=\"idle\"}[5m])) by (instance)) * 100) or avg(instance:up{group=\"research_repo\"}*99) by (instance)",
     "legendFormat": "Used CPU"
    },
    {
     "expr": "((1 - (node_memory_MemAvailable_bytes{group=\"research_repo\"} / (node_memory_MemTotal_bytes{group=\"research_repo\"}))) * 100) or on(instance,server_name) (instance:up{group=\"research_repo\"}*99)",
     "legendFormat": "Used RAM"
    },
    {
     "expr": "(avg((1 - (node_filesystem_avail_bytes{group=\"research_repo\", mountpoint=\"/\",fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes {group=\"research_repo\", mountpoint=\"/\",fstype=~\"ext4|xfs\"})) * 100) by (instance)) or avg(instance:up{group=\"research_repo\"}*99) by (instance)",
     "legendFormat": "Used Disk Space"
    },
    {
     "expr": "((1 - (node_filesystem_avail_bytes{group=\"research_repo\", mountpoint=~\"/.+\",fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes {group=\"research_repo\", mountpoint=~\"/.+\",fstype=~\"ext4|xfs\"})) * 100) or on(instance,server_name) (instance:up{group=\"research_repo\"}*99)"
    }
   ]
  },
  {
   "title": "ETL Repository",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "((1 - avg(irate(node_cpu_seconds_total{group=\"repo\", mode=\"idle\"}[5m])) by (instance)) * 100) or avg(instance:up{group=\"repo\"}*99) by (instance)",
     "legendFormat": "Used CPU"
    },
    {
     "expr": "((1 - (node_memory_MemAvailable_bytes{group=\"repo\"} / (node_memory_MemTotal_bytes{group=\"repo\"}))) * 100) or on(instance,server_name) (instance:up{group=\"repo\"}*99)",
     "legendFormat": "Used RAM"
    },
    {
     "expr": "(avg((1 - (node_filesystem_avail_bytes{group=\"repo\", mountpoint=\"/\",fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes {group=\"repo\", mountpoint=\"/\",fstype=~\"ext4|xfs\"})) * 100) by (instance)) or avg(instance:up{group=\"repo\"}*99) by (instance)",
     "legendFormat": "Used Disk Space"
    },
    {
     "expr": "(avg((1 - (node_filesystem_avail_bytes{group=\"repo\", mountpoint=\"/mnt/sdb1\",fstype=~\"ext4\"} / node_filesystem_size_bytes {group=\"repo\", mountpoint=\"/mnt/sdb1\",fstype=~\"ext4\"})) * 100) by (instance)) or avg(instance:up{group=\"repo\"}*99) by (instance)"
    },
    {
     "expr": "((1 - (node_filesystem_avail_bytes{group=\"repo\", mountpoint=~\"/mnt/sdc1\",fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes {group=\"repo\", mountpoint=~\"/mnt/sdc1\",fstype=~\"ext4|xfs\"})) * 100) or on(instance,server_name) (instance:up{group=\"repo\"}*99)"
    }
   ]
  },
  {
   "title": "Infrastructure",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "((1 - avg(irate(node_cpu_seconds_total{group=\"prometheus\", mode=\"idle\"}[5m])) by (instance)) * 100) or avg(instance:up{group=\"prometheus\"}*99) by (instance)",
     "legendFormat": "Used CPU"
    },
    {
     "expr": "((1 - (node_memory_MemAvailable_bytes{group=\"prometheus\"} / (node_memory_MemTotal_bytes{group=\"prometheus\"}))) * 100) or on(instance,server_name) (instance:up{group=\"prometheus\"}*99)",
     "legendFormat": "Used RAM"
    },
    {
     "expr": "(avg((1 - (node_filesystem_avail_bytes{group=\"prometheus\", mountpoint=\"/\",fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes {group=\"prometheus\", mountpoint=\"/\",fstype=~\"ext4|xfs\"})) * 100) by (instance)) or avg(instance:up{group=\"prometheus\"}*99) by (instance)",
     "legendFormat": "Used Disk Space"
    },
    {
     "expr": "((1 - (node_filesystem_avail_bytes{group=\"prometheus\", mountpoint=~\"/.+\",fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes {group=\"prometheus\", mountpoint=~\"/.+\",fstype=~\"ext4|xfs\"})) * 100) or on(instance,server_name) (instance:up{group=\"prometheus\"}*99)"
    }
   ]
  }
 ]
}