{
 "title": "Sysadmin_Dashboard_Longterm",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 0 },
   "options": {
    "content": "<h1><img src=\"https://www.company.org/logo.png\" width =\"100\" height =\"100\" alt=\"logo\"/>My Logo</h1>\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 7, "x": 10, "y": 0 },
   "options": {
    "content": "<br>\n<h1 style=\"color:white;\"><strong>Longterm Dashboard </strong></h1>\n\n\n"
   }
  },
  { "title": "Time", "type": "grafana-clock-panel", "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 } },
  { "title": "Databases", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "RAM Usage Databases",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short", "label": "Used RAM [%]" }
   ],
   "targets": [
    {
     "expr": "((1 - (node_memory_MemAvailable_bytes{group=\"database\"} / (node_memory_MemTotal_bytes{group=\"database\"}))) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Used Disk Space Databases (sdb1)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short", "label": "Used Disk Space [%]" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{group=\"database\",mountpoint=~\"/.+\",fstype=~\"ext4|xfs\"} * 100) / node_filesystem_size_bytes {group=\"database\",mountpoint=~\"/.+\",fstype=~\"ext4|xfs\"})\n",
     "legendFormat": "{{instance}} on {{mountpoint}}"
    }
   ]
  },
  { "title": "ETL-Worker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "RAM Usage ETL-Worker",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "Used RAM [%]" }
   ],
   "targets": [
    {
     "expr": "((1 - (node_memory_MemAvailable_bytes{group=\"etl_worker\"} / (node_memory_MemTotal_bytes{group=\"etl_worker\"}))) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Used Disk Space ETL-Worker",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "Used Disk Space [%]" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{group=\"etl_worker\",mountpoint=\"/\",fstype=~\"ext4|xfs\"} * 100) / node_filesystem_size_bytes {group=\"etl_worker\",mountpoint=\"/\",fstype=~\"ext4|xfs\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}