global:
  slack_api_url: 'https://hooks.slack.com/services/...'
  resolve_timeout: 5m
route:
  group_by: [alertname, datacenter, app]
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'slack-notification'
receivers:
- name: 'slack-notification'
  slack_configs:
  - channel: '#prometheus-alerts'
    send_resolved: true
    title: '{{ template "slack.my.title" . }}'
    text: '{{ template "slack.my.text" . }}'
    http_config:
      proxy_url: 'http://proxy.org'
templates:
- 'my.tmpl'
